# Generated by Django 4.2.7 on 2025-10-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('allrounder', 'All-rounder'), ('wicketkeeper', 'Wicket-keeper')], default='batsman', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('season', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('toss_decision', models.CharField(blank=True, choices=[('bat', 'Bat'), ('field', 'Field')], max_length=10)),
                ('result', models.CharField(default='normal', max_length=10)),
                ('dl_applied', models.BooleanField(default=False)),
                ('win_by_runs', models.IntegerField(default=0)),
                ('win_by_wickets', models.IntegerField(default=0)),
                ('venue', models.CharField(max_length=200)),
                ('umpire1', models.CharField(blank=True, max_length=100)),
                ('umpire2', models.CharField(blank=True, max_length=100)),
                ('umpire3', models.CharField(blank=True, max_length=100)),
                ('player_of_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipl_app.player')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='ipl_app.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='ipl_app.team')),
                ('toss_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_wins', to='ipl_app.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='ipl_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('is_super_over', models.BooleanField(default=False)),
                ('wide_runs', models.IntegerField(default=0)),
                ('bye_runs', models.IntegerField(default=0)),
                ('legbye_runs', models.IntegerField(default=0)),
                ('noball_runs', models.IntegerField(default=0)),
                ('penalty_runs', models.IntegerField(default=0)),
                ('batsman_runs', models.IntegerField(default=0)),
                ('extra_runs', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('dismissal_kind', models.CharField(blank=True, max_length=20)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_deliveries', to='ipl_app.player')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_deliveries', to='ipl_app.team')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_deliveries', to='ipl_app.player')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_deliveries', to='ipl_app.team')),
                ('fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielding', to='ipl_app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ipl_app.match')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker_deliveries', to='ipl_app.player')),
                ('player_dismissed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='ipl_app.player')),
            ],
        ),
    ]
